"""empty message

Revision ID: 0092e13ddd51
Revises: 4a9d4f4e9ce7
Create Date: 2023-03-05 21:09:25.487017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0092e13ddd51'
down_revision = '4a9d4f4e9ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_parent', sa.Integer(), nullable=True))
        batch_op.drop_column('parent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('id_parent')

    # ### end Alembic commands ###
