"""empty message

Revision ID: 01f2664947e4
Revises: 88a3560edcf5
Create Date: 2023-04-19 12:03:01.483414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01f2664947e4'
down_revision = '88a3560edcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_measure_unit', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.CHAR(length=2),
               type_=sa.CHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_measure_unit', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.CHAR(length=4),
               type_=mysql.CHAR(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###
