"""empty message

Revision ID: 0e95970cab82
Revises: 3d1e21fc4855
Create Date: 2023-04-01 09:34:53.312089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e95970cab82'
down_revision = '3d1e21fc4855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_cart_shopping',
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_customer', 'id_product', 'color', 'size')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('b2b_cart_shopping')
    # ### end Alembic commands ###
