"""empty message

Revision ID: 131d0fd3f3c3
Revises: f61dd6d42531
Create Date: 2023-02-23 22:07:16.823665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '131d0fd3f3c3'
down_revision = 'f61dd6d42531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.CHAR(length=1),
               comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor, U = User',
               existing_comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor',
               existing_nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('type',
               existing_type=mysql.CHAR(length=1),
               comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor',
               existing_comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor, U = User',
               existing_nullable=False)

    # ### end Alembic commands ###
