"""empty message

Revision ID: 1482143240a5
Revises: 01f2664947e4
Create Date: 2023-04-23 10:21:59.460664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1482143240a5'
down_revision = '01f2664947e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmm_legal_entity_contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_legal_entity', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.CHAR(length=1), nullable=False, comment='E = E-mail, P = Phone'),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('is_whatsapp', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_id', sa.Integer(), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    with op.batch_alter_table('cmm_products_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orign_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('cmm_products_grid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orign_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('cmm_products_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('cmm_products_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_types', schema=None) as batch_op:
        batch_op.drop_column('origin_id')

    with op.batch_alter_table('cmm_products_models', schema=None) as batch_op:
        batch_op.drop_column('origin_id')

    with op.batch_alter_table('cmm_products_grid', schema=None) as batch_op:
        batch_op.drop_column('orign_id')

    with op.batch_alter_table('cmm_products_categories', schema=None) as batch_op:
        batch_op.drop_column('orign_id')

    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('origin_id')

    op.drop_table('cmm_legal_entity_contact')
    # ### end Alembic commands ###
