"""empty message

Revision ID: 17e13afdfdd6
Revises: 75e55c4b5b32
Create Date: 2023-03-08 13:54:59.119531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e13afdfdd6'
down_revision = '75e55c4b5b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticate', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.drop_column('is_authenticate')

    # ### end Alembic commands ###
