"""empty message

Revision ID: 1926387b120d
Revises: 8ce03b017874
Create Date: 2023-02-28 17:40:16.694731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1926387b120d'
down_revision = '8ce03b017874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_collection_price',
    sa.Column('id_collection', sa.Integer(), nullable=False),
    sa.Column('id_table_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_collection', 'id_table_price')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('b2b_collection_price')
    # ### end Alembic commands ###
