"""empty message

Revision ID: 1c0b2edbca49
Revises: 4fabf5f6a114
Create Date: 2023-05-08 18:17:53.241104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c0b2edbca49'
down_revision = '4fabf5f6a114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_state_region', sa.Integer(), nullable=False))
        batch_op.drop_column('id_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('id_state_region')

    # ### end Alembic commands ###
