"""empty message

Revision ID: 3d1e21fc4855
Revises: d337126c894a
Create Date: 2023-04-01 08:54:13.327653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d1e21fc4855'
down_revision = 'd337126c894a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('discount',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('discount_percentage',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('b2b_table_price_product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Valor de Preço do Atacado',
               existing_nullable=False)
        batch_op.alter_column('price_retail',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='Valor de Preço do Varejo',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_table_price_product', schema=None) as batch_op:
        batch_op.alter_column('price_retail',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_comment='Valor de Preço do Varejo',
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_comment='Valor de Preço do Atacado',
               existing_nullable=False)

    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.alter_column('discount_percentage',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
