"""empty message

Revision ID: 3f8d24d9f054
Revises: f9b552eff4c5
Create Date: 2023-04-14 10:20:15.318866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8d24d9f054'
down_revision = 'f9b552eff4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integrated', sa.Boolean(), nullable=False, comment='Indica se o pedido foi integrado com o ERP do cliente (se houver necessidade)'))
        batch_op.add_column(sa.Column('integration_number', sa.Integer(), nullable=True, comment='Número do pedido no sistema de cliente'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.drop_column('integration_number')
        batch_op.drop_column('integrated')

    # ### end Alembic commands ###
