"""empty message

Revision ID: 448f406e0bfd
Revises: 9f5503689a93
Create Date: 2023-05-08 16:00:58.551364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '448f406e0bfd'
down_revision = '9f5503689a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmm_legal_entities_old')
    with op.batch_alter_table('cmm_country', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', mysql.VARCHAR(length=10), nullable=False))

    op.create_table('cmm_legal_entities_old',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('taxvat', mysql.VARCHAR(length=30), nullable=False, comment='CPF ou CNPJ no Brasil'),
    sa.Column('state_region', mysql.CHAR(length=2), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('neighborhood', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('type', mysql.CHAR(length=1), nullable=False, comment='C = Customer(Cliente), R = Representative(Representante), S = Supplier(Fornecedor)'),
    sa.Column('trash', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.Column('origin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fantasy_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
