"""empty message

Revision ID: 59a8bd6a2641
Revises: ad6a03fbbf70
Create Date: 2023-05-05 16:31:10.523782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a8bd6a2641'
down_revision = 'ad6a03fbbf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmm_legal_entity_web',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_legal_entity', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('web_type', sa.CHAR(length=1), nullable=False, comment='W = Website, B = Blog, S = Social Media, L = Location (latitude,longitude)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmm_legal_entity_web')
    # ### end Alembic commands ###
