"""empty message

Revision ID: 5e0bce002d29
Revises: db7f4fb2c742
Create Date: 2023-04-09 17:59:57.723034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e0bce002d29'
down_revision = 'db7f4fb2c742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_product_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_order', sa.SmallInteger(), nullable=True))
        batch_op.alter_column('limited',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('cmm_products_images', schema=None) as batch_op:
        batch_op.alter_column('img_default',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_images', schema=None) as batch_op:
        batch_op.alter_column('img_default',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('b2b_product_stock', schema=None) as batch_op:
        batch_op.alter_column('limited',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('in_order')

    # ### end Alembic commands ###
