"""empty message

Revision ID: 68f9dfb529f0
Revises: 63657820be09
Create Date: 2023-02-23 19:27:14.553845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f9dfb529f0'
down_revision = '63657820be09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmm_product_grid_distribution')
    op.drop_table('cmm_customers')
    op.drop_table('cmm_customers_group')
    op.drop_table('cmm_product_grid')
    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('token_expire', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cmm_users_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cmm_users_token'))
        batch_op.drop_column('token_expire')
        batch_op.drop_column('token')

    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('discount')

    op.create_table('cmm_product_grid',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('trash', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cmm_customers_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('need_approvement', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.Column('trash', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cmm_customers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('taxvat', mysql.VARCHAR(length=30), nullable=False, comment='CPF ou CNPJ no Brasil'),
    sa.Column('state_region', mysql.CHAR(length=2), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('neighborhood', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('date_updated', mysql.DATETIME(), nullable=True),
    sa.Column('trash', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cmm_product_grid_distribution',
    sa.Column('id_grid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_percent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_grid', 'color', 'size'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
