"""empty message

Revision ID: 6bce5793a686
Revises: 96ef55766f42
Create Date: 2023-02-21 22:37:54.889760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bce5793a686'
down_revision = '96ef55766f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('size', sa.String(length=5), nullable=False))

    with op.batch_alter_table('b2b_payment_conditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    with op.batch_alter_table('cmm_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    with op.batch_alter_table('cmm_product_grid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    with op.batch_alter_table('cmm_products_sku', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('crm_funnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    with op.batch_alter_table('crm_funnel_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_funnel_stage', schema=None) as batch_op:
        batch_op.drop_column('trash')

    with op.batch_alter_table('crm_funnel', schema=None) as batch_op:
        batch_op.drop_column('trash')

    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('cmm_products_sku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.drop_column('trash')

    with op.batch_alter_table('cmm_product_grid', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')
        batch_op.drop_column('trash')

    with op.batch_alter_table('cmm_customers', schema=None) as batch_op:
        batch_op.drop_column('trash')

    with op.batch_alter_table('b2b_payment_conditions', schema=None) as batch_op:
        batch_op.drop_column('trash')

    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('color')

    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.drop_column('trash')

    # ### end Alembic commands ###
