"""empty message

Revision ID: 75e55c4b5b32
Revises: 0092e13ddd51
Create Date: 2023-03-06 11:22:14.705851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e55c4b5b32'
down_revision = '0092e13ddd51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_category', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.drop_column('id_category')

    # ### end Alembic commands ###
