"""empty message

Revision ID: 76af272d1d04
Revises: bdfb228bbf9d
Create Date: 2023-05-08 16:22:10.840300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76af272d1d04'
down_revision = 'bdfb228bbf9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronym', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_state', schema=None) as batch_op:
        batch_op.drop_column('acronym')

    # ### end Alembic commands ###
