"""empty message

Revision ID: 76e190edb3cc
Revises: 6c899f006576
Create Date: 2023-03-24 14:27:42.935615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e190edb3cc'
down_revision = '6c899f006576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('trash', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('b2b_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_brand', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_collection', schema=None) as batch_op:
        batch_op.drop_column('id_brand')

    op.drop_table('b2b_brand')
    # ### end Alembic commands ###
