"""empty message

Revision ID: 80ab56a007e0
Revises: e0aef24fcf15
Create Date: 2023-04-17 17:03:41.288990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80ab56a007e0'
down_revision = 'e0aef24fcf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.drop_column('make_online')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make_online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='Os pedidos do sistema podem ser online ou offline'))

    # ### end Alembic commands ###
