"""empty message

Revision ID: 811a7ecd7039
Revises: b89676f5a1f4
Create Date: 2023-03-27 15:43:40.537157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811a7ecd7039'
down_revision = 'b89676f5a1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_colors_translate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    with op.batch_alter_table('cmm_sizes_translate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_sizes_translate', schema=None) as batch_op:
        batch_op.drop_column('trash')

    with op.batch_alter_table('cmm_colors_translate', schema=None) as batch_op:
        batch_op.drop_column('trash')

    # ### end Alembic commands ###
