"""empty message

Revision ID: 82ad47481343
Revises: 9428740c651a
Create Date: 2023-03-27 21:26:44.918922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ad47481343'
down_revision = '9428740c651a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_translate_colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_translate_colors', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
