"""empty message

Revision ID: 88a3560edcf5
Revises: afee46b0cbcb
Create Date: 2023-04-19 11:45:33.684024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a3560edcf5'
down_revision = 'afee46b0cbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmm_measure_unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.CHAR(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmm_measure_unit')
    # ### end Alembic commands ###
