"""empty message

Revision ID: 9428740c651a
Revises: 6f8c1bdb1b66
Create Date: 2023-03-27 16:36:19.504041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9428740c651a'
down_revision = '6f8c1bdb1b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmm_products_sku')
    with op.batch_alter_table('b2b_table_price_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('size', sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_table_price_product', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('color')

    op.create_table('cmm_products_sku',
    sa.Column('id_product', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id_product', 'color', 'size'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
