"""empty message

Revision ID: 946882ecb941
Revises: da561115333b
Create Date: 2023-02-21 14:35:54.768828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946882ecb941'
down_revision = 'da561115333b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_grid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_grid', schema=None) as batch_op:
        batch_op.drop_column('trash')

    # ### end Alembic commands ###
