"""empty message

Revision ID: 99deeb7dadcd
Revises: cd3012cc844a
Create Date: 2023-02-22 13:57:41.858969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99deeb7dadcd'
down_revision = 'cd3012cc844a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.CHAR(length=1),
               comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor',
               existing_comment='A = Administrador, L = Lojista, R = Representante',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.CHAR(length=1),
               comment='A = Administrador, L = Lojista, R = Representante',
               existing_comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor',
               existing_nullable=False)

    with op.batch_alter_table('b2b_orders_products', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
