"""empty message

Revision ID: 9f5503689a93
Revises: 59a8bd6a2641
Create Date: 2023-05-08 15:34:49.391316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f5503689a93'
down_revision = '59a8bd6a2641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmm_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_state', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmm_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmm_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_country', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_country', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_state', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_city', sa.Integer(), nullable=False))
        batch_op.drop_column('city')
        batch_op.drop_column('state_region')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_region', mysql.CHAR(length=2), nullable=False))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('id_city')
        batch_op.drop_column('id_state')
        batch_op.drop_column('id_country')

    op.drop_table('cmm_state')
    op.drop_table('cmm_country')
    op.drop_table('cmm_city')
    # ### end Alembic commands ###
