"""empty message

Revision ID: ab212e9daa9e
Revises: d54680e8793f
Create Date: 2023-03-17 13:49:27.377797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab212e9daa9e'
down_revision = 'd54680e8793f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmm_product_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type', sa.Integer(), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('id_type')

    op.drop_table('cmm_product_image')
    # ### end Alembic commands ###
