"""empty message

Revision ID: ad6a03fbbf70
Revises: e3ff31ba15ab
Create Date: 2023-04-25 11:03:38.450557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6a03fbbf70'
down_revision = 'e3ff31ba15ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fantasy_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.drop_column('fantasy_name')

    # ### end Alembic commands ###
