"""empty message

Revision ID: ae8d855bdf7f
Revises: 2dced81adec8
Create Date: 2023-03-20 10:22:56.553387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae8d855bdf7f'
down_revision = '2dced81adec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_pdv',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.alter_column('price_pdv',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
