"""empty message

Revision ID: afee46b0cbcb
Revises: eddfaf63eb54
Create Date: 2023-04-19 10:07:28.464415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afee46b0cbcb'
down_revision = 'eddfaf63eb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_company', sa.String(length=30), nullable=True, comment='Nome da empresa de transporte'))
        batch_op.add_column(sa.Column('invoice_serie', sa.Integer(), nullable=True))
        batch_op.alter_column('invoice_number',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Número da nota fiscal',
               existing_comment='Nùmero da nota fiscal',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Nùmero da nota fiscal',
               existing_comment='Número da nota fiscal',
               existing_nullable=True)
        batch_op.drop_column('invoice_serie')
        batch_op.drop_column('track_company')

    # ### end Alembic commands ###
