"""empty message

Revision ID: b0796f788579
Revises: 5e0bce002d29
Create Date: 2023-04-14 09:55:42.288081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0796f788579'
down_revision = '5e0bce002d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value', sa.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('installments', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.drop_column('installments')
        batch_op.drop_column('total_value')

    # ### end Alembic commands ###
