"""empty message

Revision ID: b89676f5a1f4
Revises: 12dbe5427dfc
Create Date: 2023-03-27 15:39:52.005695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89676f5a1f4'
down_revision = '12dbe5427dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_colors_translate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('cmm_sizes_translate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_sizes_translate', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('cmm_colors_translate', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
