"""empty message

Revision ID: bdfb228bbf9d
Revises: 448f406e0bfd
Create Date: 2023-05-08 16:15:50.711408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdfb228bbf9d'
down_revision = '448f406e0bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.drop_column('id_state')
        batch_op.drop_column('id_country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_country', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
