"""empty message

Revision ID: d1f5ed081759
Revises: ea5a321c2eff
Create Date: 2023-03-27 15:31:15.601734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f5ed081759'
down_revision = 'ea5a321c2eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmm_color_translate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hexcode', sa.String(length=8), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmm_size_translate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size_name', sa.String(length=10), nullable=True),
    sa.Column('size', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmm_size_transalte')
    op.drop_table('cmm_color_translate')
    # ### end Alembic commands ###
