"""empty message

Revision ID: d54680e8793f
Revises: 79da6e949a7e
Create Date: 2023-03-13 12:14:33.609608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd54680e8793f'
down_revision = '79da6e949a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.alter_column('instagram',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entities', schema=None) as batch_op:
        batch_op.alter_column('instagram',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
