"""empty message

Revision ID: da561115333b
Revises: f90351a27fe1
Create Date: 2023-02-21 14:17:53.085512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da561115333b'
down_revision = 'f90351a27fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_grid_distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_grid', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_grid_distribution', schema=None) as batch_op:
        batch_op.drop_column('id_grid')

    # ### end Alembic commands ###
