"""empty message

Revision ID: db7f4fb2c742
Revises: 0e95970cab82
Create Date: 2023-04-01 16:09:33.402340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7f4fb2c742'
down_revision = '0e95970cab82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_images', schema=None) as batch_op:
        batch_op.drop_column('img_default')

    # ### end Alembic commands ###
