"""empty message

Revision ID: e3ff31ba15ab
Revises: 1482143240a5
Create Date: 2023-04-23 10:25:30.889974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ff31ba15ab'
down_revision = '1482143240a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entity_contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_legal_entity_contact', schema=None) as batch_op:
        batch_op.drop_column('is_default')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
