"""empty message

Revision ID: eddfaf63eb54
Revises: 80ab56a007e0
Create Date: 2023-04-17 17:23:24.695619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddfaf63eb54'
down_revision = '80ab56a007e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.Integer(), nullable=True, comment='Nùmero da nota fiscal'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
