"""empty message

Revision ID: f5d9feb03ae4
Revises: ae8d855bdf7f
Create Date: 2023-03-20 10:38:53.047155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5d9feb03ae4'
down_revision = 'ae8d855bdf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_model', sa.Integer(), nullable=False))

    with op.batch_alter_table('cmm_products_sku', schema=None) as batch_op:
        batch_op.drop_column('id_type')
        batch_op.drop_column('id_model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_sku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_model', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    with op.batch_alter_table('cmm_products', schema=None) as batch_op:
        batch_op.drop_column('id_model')

    # ### end Alembic commands ###
