"""empty message

Revision ID: f67f60b82e1b
Revises: b91a133ebea1
Create Date: 2023-02-24 08:46:45.254723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f67f60b82e1b'
down_revision = 'b91a133ebea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.CHAR(length=1),
               comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor, U = User',
               existing_comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor',
               existing_nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('crm_funnel_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_funnel', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_funnel_stage', schema=None) as batch_op:
        batch_op.drop_column('id_funnel')

    with op.batch_alter_table('cmm_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('type',
               existing_type=mysql.CHAR(length=1),
               comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor',
               existing_comment='A = Administrador, L = Lojista, R = Representante, V = Vendedor, U = User',
               existing_nullable=False)

    # ### end Alembic commands ###
