"""empty message

Revision ID: f90351a27fe1
Revises: 96ef55766f42
Create Date: 2023-02-21 13:53:34.761924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f90351a27fe1'
down_revision = '96ef55766f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_sku', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cmm_products_sku', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
