"""empty message

Revision ID: f9b552eff4c5
Revises: b0796f788579
Create Date: 2023-04-14 10:01:28.122816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b552eff4c5'
down_revision = 'b0796f788579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_value', sa.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.drop_column('installment_value')

    # ### end Alembic commands ###
