INSERT INTO sys_state_regions(id,id_country,acronym,name) values(11,1,'RR','Rondônia');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(12,1,'AC','Acre');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(13,1,'AM','Amazonas');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(14,1,'RR','Roraima');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(15,1,'PA','Pará');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(16,1,'AP','Amapá');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(17,1,'TO','Tocantins');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(21,1,'MA','Maranhão');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(22,1,'PI','Piauí');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(23,1,'CE','Ceará');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(24,1,'RN','Rio Grande do Norte');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(25,1,'PB','Paraíba');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(26,1,'PE','Pernambuco');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(27,1,'AL','Alagoas');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(28,1,'SE','Sergipe');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(29,1,'BA','Bahia');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(31,1,'MG','Minas Gerais');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(32,1,'ES','Espírito Santo');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(33,1,'RJ','Rio de Janeiro');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(35,1,'SP','São Paulo');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(41,1,'PR','Paraná');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(42,1,'SC','Santa Catarina');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(43,1,'RS','Rio Grande do Sul');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(50,1,'MS','Mato Grosso do Sul');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(51,1,'MT','Mato Grosso');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(52,1,'GO','Goiás');
INSERT INTO sys_state_regions(id,id_country,acronym,name) values(53,1,'DF','Distrito Federal');